#!/bin/sh

root_dir=`realpath "$(dirname "$0")"/..`

# Nice! 🌈
BLUE='\033[0;34m'
NC='\033[0m' # No Color

function buildModule() {
  echo "${BLUE}Building module: $1${NC}"
  npm run -C $1 build
}

modules=(
  'modules/fibonacci'
  'modules/board'
  'spa'
)

set -euo pipefail

cd $root_dir

for i in "${modules[@]}"; do buildModule "$i";  done
