#!/bin/sh

root_dir=`realpath "$(dirname "$0")"/..`
. "$root_dir/dev-tools/base"

function buildModule() {
  echo "${BLUE}Building module: $1${NC}"
  npm run -C $1 build
}

set -euo pipefail

cd $root_dir

for i in "${modules[@]}"; do buildModule "$i";  done
